Repository likelion-14-project/lego-market, pull requests merged in 2022-07, with the labels that each got.

#65 :sparkles: 이미지 업로드 추가 및 삭제버튼 구현
  src/components/postupload/PostUpload.jsx
  src/routes/Router.jsx
Labels: ✨ Add

#87 ✨ PostDetail 페이지 구현 + 댓글컴포넌트 연결+inputFooter 연결
  src/components/comment/CommentCard.jsx
  src/components/comment/PostComment.jsx
  src/components/home/Post.jsx
  src/components/postdetail/PostDetail.jsx
  src/components/ui/InputFooter.jsx
  src/pages/PostDetailPage.jsx
  src/routes/Router.jsx
  src/utils/DateUtil.js
Labels: ✨ Add

#92 ♻️ postupload 버튼 비활성화 개선 및 서버 전송완료
  src/components/postupload/PostUpload.jsx
Labels: ✨ Add

#96 :lipstick: 맞팔상태,링크연결,ui변경
  src/components/follow/Follow.jsx
  src/components/follow/FollowCard.jsx
Labels: ✨ Add

#102 ✨ Feat/delete comment: 댓글 삭제 및 모달창 구분 완료
  src/components/comment/CommentCard.jsx
  src/components/comment/PostComment.jsx
  src/components/postdetail/PostDetail.jsx
  src/hooks/useDelete.js
Labels: ✨ Add

#105 Token check
  public/icons/icon-404.png
  public/images/Loading.png
  public/index.html
  src/components/login/Login.jsx
  src/pages/LoadingPage.jsx
  src/pages/NotFoundPage.jsx
  src/routes/Router.jsx
Labels: ✨ Add

#111 Bug
  src/components/profile/Profile.jsx
  src/components/profile/ProfileModification.jsx
  src/hooks/useProfile.js
Labels: 🐛 bug

#116 ✨ 채팅리스트 -> 채팅룸으로 가는 페이지 추가
  public/images/LegoDefaultImage.png
  public/images/chatlego1.png
  public/images/chatlego2.png
  src/components/chat/Chat.jsx
  src/components/chat/Chat.style.js
  src/components/chat/ChatList.jsx
  src/components/chat/ChatList.style.js
  src/components/chat/dataChat.json
  src/components/ui/NavBar.jsx
  src/pages/ChatPage.jsx
  src/routes/Router.jsx
Labels: ✨ Add

#120 ♻️ 스타일 컴포넌트 분리 및 헤더 푸터-> 추가 기능 추가
  src/components/chat/Chat.jsx
  src/components/chat/ChatList.jsx
  src/components/comment/Comment.style.js
  src/components/comment/CommentCard.jsx
  src/components/comment/PostComment.jsx
  src/components/postdetail/PostDetail.jsx
  src/components/postdetail/PostDetail.style.js
  src/components/ui/inputfooter/InputFooter.jsx
  src/components/ui/inputfooter/inputFooter.style.js
Labels: ♻️ refactoring

#122 ♻️ post upload 페이지 헤더 수정, 스타일 컴포넌트 분리
  src/components/postupload/PostUpload.jsx
  src/components/postupload/PostUpload.style.js
  src/components/ui/TopAdd.jsx
Labels: ♻️ refactoring

#126 ♻️ 댓글 프로필 링크 추가 및 유틸 폴더 삭제 및 함수 이동
  src/components/comment/CommentCard.jsx
  src/components/comment/DateUtil.js
  src/components/comment/PostComment.jsx
  src/components/postdetail/PostDetail.jsx
Labels: ♻️ refactoring
